In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [2]:
df = pd.read_excel("project_car_data.xlsx")

In [3]:
df

,Year,Make/Model,Male,Female,Unknown,Total,Male.1,Female.1,Unknown.1,Highway,Displacement,Tiresize,Wheelbase,GroundClearance,Cargo,Weight
0,2013,AUDI A4,202037,59936,13629,275602,0.733075,0.217473,0.049452,67,1968,225,111.00,7.1,17.0,3318.0
1,2013,AUDI A3,144962,97033,14460,256455,0.565253,0.378363,0.056384,49,1395,205,102.40,4.3,12.9,2800.0
2,2013,CITROEN C3,78551,98254,9893,186698,0.420738,0.526272,0.052989,51,1398,185,97.10,5.4,10.6,2458.0
3,2013,FIAT 500,30349,102113,8177,140639,0.215794,0.726065,0.058142,36,1368,195,90.60,4.1,14.5,2304.0
4,2013,CITROEN C4,79604,42130,5547,127281,0.625419,0.331000,0.043581,42,1560,205,102.20,5.6,12.6,2819.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023,1994,VOLVO 142,7,3,2,12,0.583333,0.250000,0.166667,20,1986,16515,103.10,7.1,21.5,2535.0
2024,1994,BMW M1,5,1,1,7,0.714286,0.142857,0.142857,32,4999,255,112.20,8.0,17.8,4199.8
2025,1994,AUDI A4,1,0,0,1,1.000000,0.000000,0.000000,67,1968,225,111.00,7.1,17.0,3318.0
2026,1994,VOLVO C70,1,0,0,1,1.000000,0.000000,0.000000,44,1560,205,103.90,5.3,14.3,2852.8
2027,1994,VOLVO S40,1,0,0,1,1.000000,0.000000,0.000000,48,1834,195,100.39,4.9,13.8,2844.0